name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y
          pip3 install -r requirements.txt

      - name: SSH into Ubuntu Server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }} # or use privateKey: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/beatnow/backend
            git pull origin main
            sudo systemctl restart backendBeatNow  # Reemplaza "your_application_service" por el nombre de tu servicio

